language: node_js
node_js:
  - "node"
branches:
  only: master
script:
  - npm run build
after_script:
  - cd dist
  - git init
  - git config user.name "guowenfu"
  - git config user.email "guowenfu@heartsone.net"
  - git add .
  - git commit -m "Travis build"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/GabrielWenFu/cfs-color.git" master:gh-pages

